apiVersion: v1 
kind: Service
metadata:
#service name is from the application.properties file
  name: profiledb
spec:
  ports:
    - port: 3306
      targetPort: profiledb-port
      protocol: TCP

  selector:
    app: profiledb

      
    
  
